# Generated by Django 6.1.1 on 2026-09-04 03:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyHousehold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('father_guardian_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
            options={
                'verbose_name': 'Family / Household',
                'verbose_name_plural': 'Families / Households',
                'ordering': ['family_id'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(blank=True, max_length=20, unique=True)),
                ('admission_date', models.DateField(default=django.utils.timezone.now)),
                ('full_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('tribe_caste', models.CharField(blank=True, max_length=100)),
                ('father_occupation', models.CharField(blank=True, max_length=100)),
                ('residence', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Withdrawn', 'Withdrawn')], default='Active', max_length=15)),
                ('inactive_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('withdrawal_date', models.DateField(blank=True, null=True)),
                ('class_at_withdrawal', models.CharField(blank=True, max_length=50)),
                ('arrears_at_withdrawal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='school.classlevel')),
                ('current_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='school.section')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.familyhousehold')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['admission_no'],
            },
        ),
        migrations.CreateModel(
            name='PromotionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=20)),
                ('promotion_date', models.DateField(auto_now_add=True)),
                ('from_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotions_from', to='school.classlevel')),
                ('from_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotions_from', to='school.section')),
                ('to_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotions_to', to='school.classlevel')),
                ('to_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotions_to', to='school.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='students.student')),
            ],
            options={
                'verbose_name': 'Promotion History',
                'verbose_name_plural': 'Promotion Histories',
                'ordering': ['-promotion_date'],
            },
        ),
    ]
