# Generated by Django 6.1.1 on 2026-09-04 03:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeeLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_ledgers', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Fee Ledger',
                'verbose_name_plural': 'Student Fee Ledgers',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'academic_session')},
            },
        ),
        migrations.CreateModel(
            name='StudentFeeMonthEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('arrears', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('exam_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('last_receipt_no', models.CharField(blank=True, max_length=50)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_entries', to='finance.studentfeeledger')),
            ],
            options={
                'verbose_name': 'Fee Month Entry',
                'verbose_name_plural': 'Fee Month Entries',
                'ordering': ['month'],
                'unique_together': {('ledger', 'month')},
            },
        ),
        migrations.CreateModel(
            name='FeePaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='students.student')),
                ('month_entries', models.ManyToManyField(related_name='payments', to='finance.studentfeemonthentry')),
            ],
            options={
                'verbose_name': 'Fee Payment Receipt',
                'verbose_name_plural': 'Fee Payment Receipts',
                'ordering': ['-id'],
            },
        ),
    ]
