# Generated by Django 6.1.1 on 2026-09-04 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Academic Session',
                'verbose_name_plural': 'Academic Sessions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('level', models.CharField(choices=[('Prep', 'Prep'), ('KG', 'KG'), ('Primary', 'Primary(1-5)'), ('Middle', 'Middle(6-8)'), ('High', 'High(9-10)'), ('Higher Secondary', 'Higher Secondary(11-12)')], max_length=20)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Class Level',
                'verbose_name_plural': 'Class Levels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Kohisar Model School & College', max_length=255)),
                ('address', models.TextField(default='Qalagay, Tehsil Barikot, District Swat, Khyber Pakhtunkhwa')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('contact', models.CharField(default='0347-0983567 / 0300-1234567', max_length=100)),
                ('academic_session_format', models.CharField(default='2025-2026', max_length=50)),
                ('receipt_no_prefix', models.CharField(default='REC-', max_length=10)),
                ('last_receipt_no', models.IntegerField(default=1000)),
            ],
            options={
                'verbose_name': 'School Setting',
                'verbose_name_plural': 'School Settings',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('class_teacher', models.CharField(blank=True, max_length=255)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='school.classlevel')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['class_level', 'name'],
                'unique_together': {('class_level', 'name')},
            },
        ),
    ]
