# Generated by Django 6.1.1 on 2026-09-04 03:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('basic_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medical_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('conveyance_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('other_allowances', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Salary Scale',
                'verbose_name_plural': 'Salary Scales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(blank=True, max_length=255)),
                ('cnic', models.CharField(blank=True, max_length=20)),
                ('dob', models.DateField()),
                ('qualification', models.TextField()),
                ('experience', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
                ('designation', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='teachers/')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('salary_scale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='teachers.salaryscale')),
            ],
            options={
                'verbose_name': 'Teacher / Staff',
                'verbose_name_plural': 'Teachers & Staff',
                'ordering': ['teacher_id'],
            },
        ),
        migrations.CreateModel(
            name='MonthlySalaryBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('base_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('days_present', models.IntegerField(default=30)),
                ('allowances', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('voucher_no', models.CharField(blank=True, max_length=50)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_bills', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Monthly Salary Bill',
                'verbose_name_plural': 'Monthly Salary Bills',
                'ordering': ['-year', '-month'],
                'unique_together': {('teacher', 'month', 'year')},
            },
        ),
    ]
